# Generated by Django 3.1.7 on 2021-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='id',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='slug',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
